#Use the following VSCode extension to quickly test endpoints
#  Name: REST Client
#  Id: humao.rest-client
#  Description: REST Client for Visual Studio Code
#  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/status HTTP/1.1

### Register
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=foo@example.com&companyName=foo&password=password

### Login (update cookie)
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=foo@example.com&password=password

### Logout (update cookie)
POST {{host}}/auth/logout HTTP/1.1

### Get my profile info (should login first)
GET {{host}}/auth/me HTTP/1.1

### Update user profile
# May returns: 202, 400, 401
# Should contains any of those fields, but at least one
PATCH {{host}}/auth/me HTTP/1.1
Content-Type: application/json

{
  "terms": [ "Company ABC", "Company DEF", "Company {{$randomInt 100 999}}" ],
  "email": "bar@{{$randomInt 10000 99000}}.example.com"
}

### Update search terms only
PATCH {{host}}/auth/me HTTP/1.1
Content-Type: application/json

{ "terms": [ "Company ABC", "Company DEF" ] }

### Update active crawlers
PATCH {{host}}/auth/me HTTP/1.1
Content-Type: application/json

{ "crawlers": ["foo", "bar"] }


### Search
GET {{host}}/search?term=ABC&type=recent HTTP/1.1
Content-Type: application/json
### 
GET {{host}}/search?term=ABC&type=popular HTTP/1.1
Content-Type: application/json
### Popular by default
GET {{host}}/search?term=ABC HTTP/1.1
Content-Type: application/json

